baseURL = "/"
languageCode = "en-us"
theme = "papaya"
title = "Customer Lab"
[[menu.main]]
identifier = "your_industry"
name = "Your Industry"
parent = "industries"
url = "/your-industry"
weight = 14
[[menu.main]]
identifier = "platforms"
name = "Platforms"
parent = "partner"
url = "/platforms/"
weight = 11
[[menu.main]]
hasChildren = true
identifier = "About us"
name = "About us"
url = "#"
weight = 1
[[menu.main]]
identifier = "live-leads"
name = "Live leads"
parent = "service"
url = "/live-leads/"
weight = 5


[[menu.main]]
hasChildren = true
identifier = "Team"
name = "Team"
url = "#"
weight = 6
[[menu.main]]
hasChildren = false
name = "FAQ"
url = "#"
weight = 13

[[menu.main]]
identifier = "local"
name = "Local services"
parent = "industries"
url = "/local/"
weight = 15
[params]
authorName = "webdevelop.pro"
dateFormat = "Jan 2, 2006"
googleAdSense = "ca-pub-0000000000000000"
googleAnalytics = "UA-000000000-1"
[[params.social.facebook]]
name = "facebook"
url = "https://facebook.com/"
weight = 30
[[params.social.instagram]]
name = "instagram"
url = "https://instagram.com/"
weight = 30
[[params.social.linkedin]]
name = "linkedin"
url = "https://linkedin.com/"
weight = 30
