baseURL = "/"
languageCode = "en-us"
theme = "papaya"
title = "Customer Lab"
[[menu.main]]
hasChildren = true
identifier = "#"
name = "Team"
url = "#"
weight = 1
[[menu.main]]
identifier = "#"
name = "Press"
url = "#"
weight = 2
[[menu.main]]
name = "Brands"
parent = "partner"
url = "/brands/"
weight = 8
[[menu.main]]
identifier = "local"
name = "Local services"
parent = "industries"
url = "/local/"
weight = 15
[params]
authorName = "webdevelop.pro"
dateFormat = "Jan 2, 2006"
googleAdSense = "ca-pub-0000000000000000"
googleAnalytics = "UA-000000000-1"
[[params.social.facebook]]
name = "facebook"
url = "https://facebook.com/"
weight = 30
[[params.social.instagram]]
name = "instagram"
url = "https://instagram.com/"
weight = 30
[[params.social.linkedin]]
name = "linkedin"
url = "https://linkedin.com/"
weight = 30
