baseURL = "/"
languageCode = "en-us"
theme = "papaya"
title = "Customer Lab"
[menu]
main = []
[params]
authorName = "webdevelop.pro"
dateFormat = "Jan 2, 2006"
googleAdSense = "ca-pub-0000000000000000"
googleAnalytics = "UA-000000000-1"
