baseURL = "/"
languageCode = "en-us"
theme = "papaya"
title = "Customer Lab"

[[menu.main]]
hasChildren = true
identifier = "About us"
name = "About us"
url = "#"
weight = 1

[[menu.main]]
hasChildren = true
identifier = "Team"
name = "Team"
url = "#"
weight = 2
[[menu.main]]
hasChildren = false
name = "Press"
url = "#"
weight = 3
[[menu.main]]
hasChildren = false
name = "FAQ"
url = "#"
weight = 4
[[menu.main]]
hasChildren = false
name = "Contacts"
url = "#"
weight = 5

[params]
authorName = "webdevelop.pro"
dateFormat = "Jan 2, 2006"
googleAdSense = "ca-pub-0000000000000000"
googleAnalytics = "UA-000000000-1"

