---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: Services
- type: directory
  path: content/live-calls
  label: Live calls
  create: all
  match: "**/*"
- type: directory
  path: content/live-leads
  label: Live leades
  create: all
  match: "**/*"
- type: directory
  path: content/managedservices
  label: Managed services
  create: all
  match: "**/*"
- type: directory
  path: content/saas
  label: Saas
  create: all
  match: "**/*"
- type: heading
  label: Industries
- type: directory
  path: content/consumerfinance
  label: Consumer finance
  create: all
  match: "**/*"
- type: directory
  path: content/insurance
  label: Insurance
  create: all
  match: "**/*"
- type: directory
  path: content/local
  label: Local services
  create: all
  match: "**/*"
- type: heading
  label: Partners
- type: directory
  path: content/publisher
  label: Publisher
  create: all
  match: "**/*"
- type: directory
  path: content/brands
  label: Brands
  create: all
  match: "**/*"
- type: directory
  path: content/platforms
  label: Platforms
  create: all
  match: "**/*"
- type: heading
  label: General
- type: directory
  path: content/main
  label: Home page
  create: all
  match: "**/*"
- type: directory
  path: content/contact-us
  label: Contact us
  create: all
  match: "**/*"
- type: directory
  path: content/privacypolicy
  label: Privacy
  create: all
  match: "**/*"
- type: directory
  path: content/termsconditions
  label: Terms
  create: all
  match: "**/*"
- type: document
  path: config.toml
  label: config.toml
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.76.5
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.76.5
